### ISSUE TITLE
Wrong Link for Slack

### ISSUE THREAD

**Issue by Oceanestars** [RocketCommunicationsInc/astro-www#127]
Hi this is super small, 
Inside [`home-community.json`](https://github.com/RocketCommunicationsInc/astro-www/blob/main/src/data/home-community.json) you have :
```
"website": {
		  "type": "link",
		  "data": {
			  "url": "https://forms.gle/NiSV47SbJFb8kAWdA",
			  "description": "Join Astro on Slack"
		     }
		}
```
The slack link on https://www.astrouxds.com/ leads to a form which requires permission to see.
Should it be this instead(disregard spacing)?
```
"website": {
		"type": "link",
		"data": {
			"url": "https://astrouxds.slack.com/",
			"description": "Join Astro on Slack"
		}
	}
```

If this is what the correct link should be, happy to make a PR!

Thanks for everything that you do!

**Comment by kiley-mitti** [comment]
Hi @Oceanestars!

Thank you so much for reaching out. You're absolutely correct that this is our AstroUXDS slack address. The reason we decided to link to the form instead of the slack channel directly is that only users with email addresses from certain domains are allowed automatic access to the channel.

We wanted to allow a method for interested users from un-whitelisted domains to join us. I'll bring this up with the team though to see if perhaps we could add both a direct link and a signup link sometime in future.

Thank you for your notice and concern! If you see any other issues you'd like to bring to our attention please don't hesitate. We're thrilled to have you as a part of the Astro community!
